version: 2.1

orbs:
  node: electronjs/node@1.4.1

commands:
  install:
    steps:
      - run: git config --global core.autocrlf input
      - node/install:
          node-version: '18.17'
      - checkout
      - node/install-packages
  load-release-secrets:
    steps:
      - run: |
          curl -X POST "$FIDDLE_SECRETS_SERVICE_ENDPOINT?format=shell" -H "Content-Type: application/json" -d '{"token":"'$CIRCLE_OIDC_TOKEN'"}' >> $BASH_ENV

jobs:
  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - install
  mac-build:
    parameters:
      arch:
        type: enum
        enum: [ 'x64', 'arm64' ]
    executor: node/macos
    steps:
      - install
      - load-release-secrets
      - run: npx yarn run publish --arch=<< parameters.arch >> --dry-run
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths:
            - out
  win-build:
    environment:
      SIGN_OR_DIE: true
    parameters:
      arch:
        type: enum
        enum: [ 'x64', 'arm64', 'ia32' ]
    executor: node/windows
    steps:
      - install
      - run: npx yarn run publish --arch=<< parameters.arch >> --dry-run
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths:
            - out
  linux-build:
    parameters:
      arch:
        type: enum
        enum: [ 'x64', 'arm64','armv7l' ]
    executor: node/linux
    resource_class: medium+
    steps:
      - run: sudo apt-get update && sudo apt install rpm squashfs-tools
      - install
      - run: npx yarn run publish --arch=<< parameters.arch >> --dry-run
      # CircleCI doesn't let you persist files with the same name from multiple
      # jobs, so only persist the .webpack path from the x64 linux-build job
      - when:
          condition:
            not:
              equal: [ << parameters.arch >>, x64 ]
          steps:
            - run: rm -rf .webpack/*
      - store_artifacts:
          path: out
      - persist_to_workspace:
          root: .
          paths:
            - out
            - .webpack
  publish-to-github:
    docker:
      - image: cimg/base:stable
    steps:
      - install
      - attach_workspace:
          at: .
      - load-release-secrets
      - run: yarn run publish --from-dry-run
  notify-sentry-deploy:
    docker:
      - image: cimg/base:stable
    environment:
      SENTRY_ORG: electronjs
      SENTRY_PROJECT: electron-fiddle
      SENTRY_ENVIRONMENT: production
    steps:
      - install
      - attach_workspace:
          at: .
      - run:
          name: Create release and notify Sentry of deploy
          command: |
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=Electron-Fiddle@${CIRCLE_TAG:1}
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits $SENTRY_RELEASE --auto
            sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps --url-prefix=~/.webpack ./.webpack/
            sentry-cli releases finalize $SENTRY_RELEASE
            sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT

workflows:
  build-and-test:
    jobs:
      - lint
      - mac-build:
          context: fiddle-release
          matrix:
            parameters:
              arch: [ x64, arm64 ]
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - win-build:
          matrix:
            parameters:
              arch: [ x64, ia32 ]
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - linux-build:
          matrix:
            parameters:
              arch: [ x64, arm64, armv7l ]
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - publish-to-github:
          context: fiddle-release
          requires:
            - lint
            - mac-build
            - win-build
            - linux-build
          filters:
            tags:
              only: 
                - /^v.*/
            branches:
              ignore: /.*/
      - notify-sentry-deploy:
          requires:
            - publish-to-github
          filters:
            tags:
              only:
                - /^v.*/
            branches:
              ignore: /.*/
